#!/usr/bin/python3

import argparse
import json
from datetime import date

import progression.util

parser = argparse.ArgumentParser()
parser.add_argument('--run', action="store_true")
parser.add_argument('--action', '-a', type=str, choices=["new", "edit", "remove"],
                    help="action to perform")
args = parser.parse_args()

if args.run:
    progression.util.start_service_loop()
    # TODO: add a finish to the this


def new_progression_visualization():
    """"""
    # Create/Fetch config directory
    config_path = progression.util.get_config_path(create_if_absent=True)

    # TODO: Automatic start and end date finder? Maybe add on to pittapi with calendar
    # term_code = input("What's the term code for the Pitt Semester (e.g. 2171)? ")

    # Data initialization
    data = {}

    data['start'] = '01/06/2020'
    data['end-date'] = '04/25/2020'
    data['breaks'] = [
        {
            "title": "springbreak",
            "start": "03/08/2020",
            "end-date": "03/15/2020"
        }
    ]
    data['exams'] = []
    data['finals'] = {
        'start': '04/20/2020',
        'end-date': '04/25/2020'
    }


actions = {
    "new": new_progression_visualization
}

actions[args.action]()
